Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -138,7 +138,34 @@ runs:
     - name: Login to docker registry
       shell: bash
       run: |
-        source ./.github/actions/jit-github-action/retry-curl.sh
+        MAX_RETRIES=3
+        # Function to retry a curl command
+        retry_curl() {
+            local retries=0
+            local base_retry_delay=3
+            local response=""
+            while [[ $retries -lt $MAX_RETRIES ]]; do
+                response=$(curl -s -w "%{http_code}" "$@")
+                curl_return_code=$?
+                echo "curl_return_code=$curl_return_code" >&2
+                status_code=${response: -3}  # Extract the status code from the response
+                # Check if the status code is one of the ones you want to retry on
+                if [[ $status_code != 104 && $status_code != 107 && $status_code != 502 && $status_code != 503 && $status_code != 504 ]]; then
+                    # If status code is not connection reset (104/107) or service unavailable (502/503/504) => break and don't retry
+                    echo "$response"
+                    return
+                fi
+                
+                ((retries++))
+                echo "Attempt #$(($retries)) returned status code: $status_code" >&2
+                if [[ $retries -lt $MAX_RETRIES ]]; then
+                  retry_delay=$(($base_retry_delay**$retries))
+                  echo "Sleeping for $retry_delay seconds" >&2
+                  sleep $retry_delay
+                fi
+            done
+            echo "$response"  # If the loop finishes, return the last response
+        }
         LOGIN_RESPONSE=$(retry_curl \
             -X POST \
             -H "Authorization: Bearer ${{ steps.oidc-auth.outputs.jit_token }}" \
