Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -265,36 +265,36 @@ runs:
         path: ci/cache/docker/
         key: ${{ steps.set-cache-file.outputs.cache_file }}@${{ steps.set-image-id.outputs.image_id }}.tar
 
-    - name: Run The Action
-      id: run-the-action
-      run: |
-        echo CONFIG_FILE_PATH=${CONFIG_FILE_PATH} > /tmp/docker_env.txt
-        echo SOURCE_CODE_FOLDER=/code >> /tmp/docker_env.txt
-        echo FAIL_ON_FINDINGS=${{ inputs.fail_on_findings }} >> /tmp/docker_env.txt
-        if [ -n "${{ inputs.security_control_output_file }}" ]
-        then
-          echo SECURITY_CONTROL_OUTPUT_FILE=${{ inputs.security_control_output_file }} >> /tmp/docker_env.txt
-        fi
-        echo "action_successful=true" >> $GITHUB_OUTPUT
-        docker run \
-          --rm \
-          ${{ inputs.inline_environment }} \
-          --env-file /tmp/docker_env.txt \
-          ${{ inputs.container_args }} \
-          -v ${CENTRALIZED_REPO_FILES_LOCATION_PATH}:/.jit \
-          ${{ env.mount_original_repo_command }} \
-          ${{ inputs.security_control }} \
-          --execution-id ${{ fromJSON(github.event.inputs.client_payload).payload.execution_id }} \
-          --event-id ${{ fromJSON(github.event.inputs.client_payload).payload.jit_event_id }} \
-          --base-url ${{ fromJSON(github.event.inputs.client_payload).payload.jit_base_api }} \
-          --jit-token ${{ steps.oidc-auth.outputs.jit_token }}
-      shell: bash
-      env:
-        # this field would set the original repo command mount command (would be mounted always in the old flow) and only if checkout = true in the new flow
-        mount_original_repo_command: ${{ fromJSON('["","-v $(pwd)/code:/code"]')[((!(fromJSON(github.event.inputs.client_payload).payload.runner_setup) || (fromJSON(github.event.inputs.client_payload).payload.runner_setup.checkout == true)))] }}
+    # - name: Run The Action
+    #   id: run-the-action
+    #   run: |
+    #     echo CONFIG_FILE_PATH=${CONFIG_FILE_PATH} > /tmp/docker_env.txt
+    #     echo SOURCE_CODE_FOLDER=/code >> /tmp/docker_env.txt
+    #     echo FAIL_ON_FINDINGS=${{ inputs.fail_on_findings }} >> /tmp/docker_env.txt
+    #     if [ -n "${{ inputs.security_control_output_file }}" ]
+    #     then
+    #       echo SECURITY_CONTROL_OUTPUT_FILE=${{ inputs.security_control_output_file }} >> /tmp/docker_env.txt
+    #     fi
+    #     echo "action_successful=true" >> $GITHUB_OUTPUT
+    #     docker run \
+    #       --rm \
+    #       ${{ inputs.inline_environment }} \
+    #       --env-file /tmp/docker_env.txt \
+    #       ${{ inputs.container_args }} \
+    #       -v ${CENTRALIZED_REPO_FILES_LOCATION_PATH}:/.jit \
+    #       ${{ env.mount_original_repo_command }} \
+    #       ${{ inputs.security_control }} \
+    #       --execution-id ${{ fromJSON(github.event.inputs.client_payload).payload.execution_id }} \
+    #       --event-id ${{ fromJSON(github.event.inputs.client_payload).payload.jit_event_id }} \
+    #       --base-url ${{ fromJSON(github.event.inputs.client_payload).payload.jit_base_api }} \
+    #       --jit-token ${{ steps.oidc-auth.outputs.jit_token }}
+    #   shell: bash
+    #   env:
+    #     # this field would set the original repo command mount command (would be mounted always in the old flow) and only if checkout = true in the new flow
+    #     mount_original_repo_command: ${{ fromJSON('["","-v $(pwd)/code:/code"]')[((!(fromJSON(github.event.inputs.client_payload).payload.runner_setup) || (fromJSON(github.event.inputs.client_payload).payload.runner_setup.checkout == true)))] }}
 
     - name: Notify Jit on Failure
-      if: failure() && steps.run-the-action.outputs.action_successful != 'true'
+      # if: failure() && steps.run-the-action.outputs.action_successful != 'true'
       uses: actions/github-script@v6
       with:
         script: |
