Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -44,9 +44,12 @@ runs:
                 fi
                 
                 ((retries++))
-                retry_delay=$(($base_retry_delay**$retries))
-                echo "Attempt #$(($retries)) returned status code: $status_code. Sleeping for $retry_delay" >&2
-                sleep $retry_delay
+                echo "Attempt #$(($retries)) returned status code: $status_code." >&2
+                if [[ $retries -lt $MAX_RETRIES ]]; then
+                  retry_delay=$(($base_retry_delay**$retries))
+                  echo "Sleeping for $retry_delay" >&2
+                  sleep $retry_delay
+                fi
             done
             echo "$response"  # If the loop finishes, return the last response
         }
