Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -44,7 +44,7 @@ runs:
                 fi
                 
                 ((retries++))
-                echo "Attempt #$(($retries)) returned status code: $status_code." >&2
+                echo "Attempt #$(($retries)) returned status code: $status_code" >&2
                 if [[ $retries -lt $MAX_RETRIES ]]; then
                   retry_delay=$(($base_retry_delay**$retries))
                   echo "Sleeping for $retry_delay" >&2
