Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -60,10 +60,18 @@ runs:
             }' \
             ${{ fromJSON(github.event.inputs.client_payload).payload.jit_base_api }}/github/auth
         )
-        AUTH_RESPONSE_BODY=${AUTH_RESPONSE:0:${#AUTH_RESPONSE}-3}
-        echo $AUTH_RESPONSE_BODY
-        echo "github_token=$(echo $AUTH_RESPONSE_BODY | jq -r '.github_token')" >> $GITHUB_OUTPUT
-        echo "jit_token=$(echo $AUTH_RESPONSE_BODY | jq -r '.jit_token')" >> $GITHUB_OUTPUT
+        
+        AUTH_RESPONSE_CODE=${AUTH_RESPONSE: -3}
+        echo "Calling OIDC Auth endpoint returned with response_code=$AUTH_RESPONSE_CODE"
+        
+        if [ $response_code = "200" ]; then
+          AUTH_RESPONSE_BODY=${AUTH_RESPONSE:0:${#AUTH_RESPONSE}-3}
+          echo "github_token=$(echo $AUTH_RESPONSE_BODY | jq -r '.github_token')" >> $GITHUB_OUTPUT
+          echo "jit_token=$(echo $AUTH_RESPONSE_BODY | jq -r '.jit_token')" >> $GITHUB_OUTPUT
+        else
+          echo "Got fatal error when calling auth oidc token with jit server"
+          exit 100
+        fi
 
     - name: Verify we have tokens
       shell: bash
